default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  etherscan:
    base_url: <%= ENV["ETHERSCAN_BASE_URL"] %>
    api_key_prefix: <%= ENV["ETHERSCAN_API_KEY_PREFIX"] %>
    api_key: <%= ENV["ETHERSCAN_API_KEY"] %>

development:
  <<: *default
  secret_key_base: 6545b135fc49cbe17e4fac4af002ae5880fc216c718d5bc17e00ba89413dcade6ad51933d8541ac035e0bf68de8240a1811a92ec37bdf522b355f080da8ac381
  domain_name: localhost:3000

test:
  <<: *default
  secret_key_base: ed727001bfd8c17a5cbc06c0ac3ef95e5226d95323b7f281879cb320ee7ab5497b12c6d834f4bcc7686b9b533bcb10ea17f19626664dee3046ff9c3a7193e124
  domain_name: test

production:
  <<: *default
